name: Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'pacalo-site/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'pacalo-site/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./pacalo-site

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: pacalo-site/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build