name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'pacalo-site/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build Vite app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: pacalo-site/package-lock.json

      - name: Install dependencies
        working-directory: pacalo-site
        run: npm ci

      - name: Build
        working-directory: pacalo-site
        run: npm run build
        env:
          VITE_BASE: /pacalo/

      - name: Create SPA fallback (404.html)
        working-directory: pacalo-site
        run: cp dist/index.html dist/404.html

      - name: Disable Jekyll on Pages
        working-directory: pacalo-site
        run: touch dist/.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pacalo-site/dist

  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
